// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
	"log"

	_ "github.com/jackc/pgx/v5/stdlib"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

func Connect(dbURL string) (*sql.DB, *Queries) {
	conn, err := sql.Open("pgx", dbURL)
	if err != nil {
		log.Fatalf("sql.Open failed: %v", err)
	}

	if err := conn.Ping(); err != nil {
		log.Fatalf("db.Ping failed: %v", err)
	}

	fmt.Println("✅ Connected to PostgreSQL")

	queries := New(conn)
	return conn, queries
}
